### ISSUE TITLE
SINCE_ID PARAMETER IS INVALID

### ISSUE THREAD

**Issue by perrycannon** [WebBreacher/trumpdroidretweeter#4]
since_id parameter is invalid.', 'code': 44

Good afternoon, i receive this error "since_id parameter is invalid.', 'code': 44"

I do not understand why.

**Comment by WebBreacher** [comment]
Did you create and insert your Twitter API key into the script? 

Can you tell me more information about your setup? Windows? Linux? Version of Python...

**Comment by perrycannon** [comment]
Yes I did insert my api keys. I am using a raspberry pi zero, with raspbian. I took the code out that takes a picture of the tweet. The raspberry pi zero isn't suited to phantomjs.

Is it ok to post the code here?

Thank you for your help.

**Comment by WebBreacher** [comment]
no. Please don't. Since you modified the code, this isn't an issue with the existing Github'd repository so I will close this issue.

If you'd like help with your new code, I'm happy to assist. At the top of the Github.com site there is something called a Gist. Click it, create a new gist, paste in your code, send me the link (webbreacher at gmail). I'll see what I can do to help you out.
